### PR TITLE
fix: async validating

### PR DESCRIPTION
**Pull request by xxleyi**
try fix https://github.com/final-form/react-final-form/issues/780

### CODE REVIEW

**Comment by gertdreyer** [comment]
Hi @xxleyi , can you please add a test that fails prior to your change and passes afterwards? Thus we can ensure we have no regression of the same issue in the future

**Comment by xxleyi** [comment]
@gertdreyer Test has already been provided by @iamdey in react-final-form, https://github.com/final-form/react-final-form/pull/1018. I tried and it worked well.

**Comment by gertdreyer** [comment]
Can you include that test in the automated testing?

**Comment by xxleyi** [comment]
@gertdreyer these are two repo, you mean I include that test in final-form?

**Comment by gertdreyer** [comment]
It should be possible to do it in a vanilla JS test in this repo - if you want to attempt that, otherwise, I am happy to merge as is due to the existing bug examples and tests being in RFF.

**Comment by xxleyi** [comment]
@gertdreyer I don't have many experience on JS test, so maybe merge firstly? I will try add test later.

**Comment by xxleyi** [comment]
@gertdreyer Sorry to bother, I added test PR https://github.com/final-form/final-form/pull/475, and we are still meeting this problem, can we publish a new version?

**Pull request merged**
