### PR TITLE
export runValidation api

### PR DESCRIPTION
**Pull request by 493636333**
hello,i have some requirement, sometimes i have to runValidation do myself, but now the api is not export.

### CODE REVIEW

**Comment by erikras** [comment]
You should never need to do this. Validation is run on every change. Why would you need this?

**Comment by 493636333** [comment]
I know validation is run every chang,but if validator is changed,validation will not run

**Comment by 493636333** [comment]
if I can do runValidation do myself? because I want run validation when other field changed or validator changed, or one of props changed, not only current field value changed

**Comment by erikras** [comment]
Can you describe your use case a little better? Which validation function is changing? Why is it changing?

**Comment by 493636333** [comment]
i have a requirement, for example, there have two fields, one is a select field(a), one is another custom component(b), there will fetch some data(sourceData) from api when a is changed, then validation of b field depend on sourceData, but now i can't call validate when sourceData is back。

**Comment by erikras** [comment]
Could you not use async validation (i.e. return a `Promise` from your validation function)?

**Comment by 493636333** [comment]
no，async data not only use in validation，custom Field need this async data，if i can run validation do myself，i think everything will be resolved。

**Pull request closed without merging**
