### PR TITLE
Optimize toPath method by caching results

### PR DESCRIPTION
**Pull request by jeslabs**
Hi,

We have some performance issue with big form (more thousand field) and we find that `toPath` method take a long time. As it is a pure fonction, by caching results, we get a significant improvement.

What do you think about this optimisation ?

Thanks in advance.

### CODE REVIEW

**Comment by erikras** [comment]
It'd be nice to have some numbers to show the improvement, but this looks okay.

Keeping a singleton of the regex can be dangerous in Javascript, since, for some reason, `RegExp` is stateful, but I think that's only when you're doing `.exec()`, not for `.split()`, so I think we're good on this one.

**Comment by erikras** [comment]
Published in [`v4.19.0`](https://github.com/final-form/final-form/releases/tag/v4.19.0).

**Comment by bertho-zero** [comment]
It would be more relevant to use a Map than a Object here.

image
from https://jsperf.com/object-vs-map/10

**Comment by ManuelBoucault** [comment]
It seems that these results are not the same for all browsers. I test Edge 18 and FF 75, and i get pretty much the same result.
image
I get your results only with Chrome.

**Pull request merged**
