### PR TITLE
handle initialize function to accept functions

### PR DESCRIPTION
**Pull request by alirezavalizade**
Usage: 

```
initialize((v) => ({ ...v, any: null }))
```

### CODE REVIEW

**Comment by erikras** [comment]
To get this merged, you'll need to update [Flow](https://github.com/final-form/final-form/blob/master/src/types.js.flow#L183) and [TS](https://github.com/final-form/final-form/blob/master/src/index.d.ts#L185) typings and the docs.

**Comment by erikras** [comment]
This pull request **introduces 3 alerts** when merging 0a199a2c0f8aa5ce85275453fb9edc03096c0775 into b2aa45545a517fb29e0bf5040030a5dc5c9b64da - [view on LGTM.com](https://lgtm.com/projects/g/final-form/final-form/rev/pr-d38df29311b84069359f73171820ca323b624686)

**new alerts:**

* 3 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by erikras** [comment]
This pull request **introduces 3 alerts** when merging 4750a2552c7291d7aaf526e762d914a76b36f16c into b2aa45545a517fb29e0bf5040030a5dc5c9b64da - [view on LGTM.com](https://lgtm.com/projects/g/final-form/final-form/rev/pr-6bf9f49ef04c1282e3f69ae2d87add5f637e1597)

**new alerts:**

* 3 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by erikras** [comment]
This pull request **introduces 3 alerts** when merging 6d224345cf410cf35816f16df8e04b11c40773e2 into b2aa45545a517fb29e0bf5040030a5dc5c9b64da - [view on LGTM.com](https://lgtm.com/projects/g/final-form/final-form/rev/pr-cc01b631df147ddcdd9f092a1064be9f7fad26ad)

**new alerts:**

* 3 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by alirezavalizade** [comment]
I'm getting this error on building it!
Do you know what is this?
```
The script called "validate" which runs "node node_modules/concurrently/src/main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold,bgGreen.bold,bgBlack.bold,bgCyan.bold" --prefix "[{name}]" --names "lint,flow,typescript,build.andTest,test" 'nps lint' 'nps flow' 'nps typescript' 'nps build.andTest' 'nps test'" failed with exit code 1
```

**Pull request closed without merging**
