### PR TITLE
Remove unnecessary `flow` dev dependency

### PR DESCRIPTION
**Pull request by pepakriz**

### CODE REVIEW

**Comment by erikras** [comment]
Why is this unnecessary? Because `flow-bin` contains it?

**Comment by pepakriz** [comment]
Because `flow` is different library with similar name. See https://www.npmjs.com/package/flow vs https://www.npmjs.com/package/flow-bin

**Comment by erikras** [comment]
Duh. 🙄 Must have been an `npm install` typo some time ago... Thanks!

**Comment by pepakriz** [comment]
Yeah, initial commit contains this typo :smile:

**Pull request merged**
