### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by erikras**
Improved performance by not sending notifications when validation is suspended, such as when mounting many fields.

### CODE REVIEW

**Comment by erikras** [comment]
Published in [`v4.6.0`](https://github.com/final-form/final-form/releases/tag/v4.6.0).

**Comment by perrin4869** [comment]
Hm... Actually, this PR is messing with my application logic.
I am expecting `final-form-calculate` to fire some changes, which get unexpectedly delayed and I could trace it back to this commit. Is there any chance to revert these changes, or add an option to turn them off?
Thanks!

**Comment by erikras** [comment]
@perrin4869 Can you make a sandbox to demonstrate your use case?

**Comment by perrin4869** [comment]
hm... won't be easy but I'll try :)
The problem in a nutshell is that am firing a `FormAPI.change` from within a react component, and I expect `final-form-calculate` to immediately fire, but it doesn't. Then I fire another `change`, and finally validation is resumed, and the `calculate` decorator finally kicks back in, undoing my second `change`.
I expect `change` -> `decorate` -> `change`, but I get `change` -> `change` -> `decorate`.
Ill setup the sandbox now anyways!

**Comment by erikras** [comment]
What component lifecycle method is your `form.change()` call in?

**Comment by perrin4869** [comment]
`componentDidMount` for the first change, `componentDidUpdate` for the second `change`

**Comment by erikras** [comment]
Interesting. I can see how that might get tangled with the validation pausing. A sandbox would still be very helpful for me to devise a solution.

**Comment by perrin4869** [comment]
https://codesandbox.io/s/vvmk4xz660

This is it.
I want the value or `bar` to be `new bar`, but it is getting `calculated bar`

**Comment by perrin4869** [comment]
Also, for some reason the form is not re-rendering after updating `foo`

**Pull request merged**
