### PR TITLE
Feature/notify form

### LINKED ISSUE #383: form.pauseValidation() prevents form subscriber from notifying
### Are you submitting a **bug report** or a **feature request**?

I'm not sure if this behavior is considered a bug or not. I don't understand why these features are so highly coupled. Thank you in advance for any help finding a workaround or letting me know the justification for this design choice.

### What is the current behavior?

When validation is paused, the form subscriber no longer notifies me of form updates. I don't understand why notification is locked behind the `validationPaused` flag.

```
let scheduleNotification: boolean = false
const notifyFormListeners = () => {
  if (notifying) {
    scheduleNotification = true
  } else {
    notifying = true
    callDebug()
    if (!inBatch && !validationPaused) {
      const { lastFormState } = state
      const nextFormState = calculateNextFormState()
      if (nextFormState !== lastFormState) {
        state.lastFormState = nextFormState
        notify(
          state.subscribers,
          nextFormState,
          lastFormState,
          filterFormState
        )
      }
    }
    notifying = false
    if (scheduleNotification) {
      scheduleNotification = false
      notifyFormListeners()
    }
  }
}
```

### What is the expected behavior?

I would expect the form subscriber to still notify me of form updates even while validation is paused.

### What's your environment?

final form: v4.20.1

### Other information

I'm bumping this from my [StackOverflow post](https://stackoverflow.com/questions/64121128/why-does-form-pausevalidation-prevent-the-form-subscriber-from-notifying). There are code references in that post.

### PR DESCRIPTION
**Pull request by Renddslow**
Fixes #383 

Hi there, I know you typically prefer beginning with a discussion, but I figured since there hadn't been any movement I'd throw together this quick solve and open it for discussion.

### CODE REVIEW

**Comment by Renddslow** [comment]
Little more background on what this solves. Today, for performance reasons, `pauseValidation` prevents the form from sending notifications. This makes sense if you're pausing for the sake of adding and removing fields in bulk, however, in some cases, we've needed to pause and resume to have some more fine grained control over order of operations.
This would allow you to specify that, when pausing notifications, that you want to take the potential performance cost of getting notifications even when paused.

**Comment by erikras** [comment]
Tests and updating the docs would be awesome.

**Comment by Renddslow** [comment]
Tests and doc have been updated.

**Comment by michaltk** [comment]
Nice feature! Any plans of getting this released?

**Comment by erikras** [comment]
Released in [`v4.20.2`](https://github.com/final-form/final-form/releases/tag/v4.20.2).

**Pull request merged**
