### PR TITLE
Added restart method to FormApi interface

### PR DESCRIPTION
**Pull request by chrisahardie**
Added missing method to FormApi.

### CODE REVIEW

**Comment by chrisapplegate** [comment]
I was about to write this PR myself as I have encountered the same Typescript problem. Please merge this in when you are producing your next release.

**Comment by kkirbatski-adig** [comment]
@chrisahardie Shouldn't `initialValues` be typed to `InitialFormValues`:

```tsx
interface FormApi<FormValues = Record<string, any>, InitialFormValues = Partial<FormValues>> {
    restart: (initialValues?: InitialFormValues) => void
}
```

**Comment by kkirby** [comment]
@chrisahardie Shouldn't `initialValues` be typed to `InitialFormValues`:

```tsx
interface FormApi<FormValues = Record<string, any>, InitialFormValues = Partial<FormValues>> {
    restart: (initialValues?: InitialFormValues) => void
}
```

**Comment by chrisahardie** [comment]
@kkirby Hmm... I did a comparison of the `reset` and `restart` implementations:

`reset: (initialValues = state.formState.initialValues) => {`

`restart: (initialValues = state.formState.initialValues) => {`

Given the `FormApi` interface describes `reset` as `reset: (initialValues?: FormValues) => void`, I did the same for `restart`.

`InitialFormValues` is the `Partial` of `FormValues`, do we expect to ever invoke `restart` where `initialValues` omits some of the `FormValues` members? Wouldn't it put the form to be in an inconsistent state where some values were reverted and some others aren't?

**Comment by kkirby** [comment]
@chrisahardie I would argue that both reset, restart and initialize should use InitialFormValues since the value inevitably gets passed to `initialize`, which takes the value and assigns it to `formState.values`. So if nothing is passed, the form is initialized with no values, but if a partial object is passed, the form has some fields sets. I've certainly created a form with only some values initialized. Though, I digress. This is outside the scope of your PR. Best to be consistent then correct for small changes like this.

**Comment by chrisahardie** [comment]
@kkirby That doesn't sound unreasonable - appreciate you taking the time to validate the direction.

**Comment by erikras** [comment]
Released in [`v4.20.2`](https://github.com/final-form/final-form/releases/tag/v4.20.2).

**Pull request merged**
