### PR TITLE
accept function as argument in initialize()

### PR DESCRIPTION
**Pull request by alirezavalizade**
Usage:
```
initialize((values) => ({ ...values, any: null }))
```

### CODE REVIEW

**Comment by alirezavalizade** [comment]
If you merge this, I'll send a pull request for `react-final-form` docs.
@erikras

**Comment by erikras** [comment]
Can you describe the use case for this?

**Comment by alirezavalizade** [comment]
Sure, Sometimes i need to change value of a field but also need to keep the current values of form,
for example: 

```
initialize({
  posts: 'a value'
})
```
If i use this other fields will lose their values. But i need to keep my current values and just change one field. and also i don't want to set values in state on changing the form. I know it's possible using `change` method in `finalForm` state but sometimes need to this. It's nice to have it.
[Take a look at this sandbox please](https://codesandbox.io/s/qm8y71wzw)

**Comment by erikras** [comment]
Well, this could be accomplished like this:

[Edit 🏁 React Final Form - Loading and Initializing](https://codesandbox.io/s/03kv4mpwml)

You have all the information you need to initialize with all the values.

**Comment by alirezavalizade** [comment]
@erikras Thanks for your reply, Yes i agree it, but really sometimes need to access current values for initialize the form. I can create another Sandbox,

**Pull request merged**
